#!/bin/bash
#script that quickly launches the parser1 file if it exists
#file paths are set up in this case
#opens the file output after running

make parser1
if (($? == 0)); then
    if(($1 == 0)); then
	./parser1 tests/parser1/test1.cpl tests/parser1/test1.output
	emacs tests/parser1/test1.output&
    elif(($1 == 1)); then
	./parser1 tests/parser1/test2.cpl tests/parser1/test2.output
	emacs tests/parser1/test2.output&
    elif(($1 == 2)); then
	./parser1 tests/parser1/fibv1.prog tests/parser1/fibv1.output
	emacs tests/parser1/fibv1.output&
    fi
else
    echo Error while compiling parser1
fi

