#!/bin/bash
#script that quickly launches the parser1 file if it exists
#file paths are set up in this case
#opens the file output after running

make parser2
if (($? == 0)); then
    ./parser2 tests/parser2/test$1.cpl tests/parser2/test$1.output
    emacs tests/parser2/test$1.output&
else
    echo Error while compiling parser2
fi


