#!/bin/bash
#script that quickly launches the comp2 file if it exists
#file paths are set up in this case
#opens the file output after running

make comp2
test_path="tests/comp2"
if (($? == 0)); then
    ./comp2 $test_path/test$1.cpl $test_path/test$1.output $test_path/test$1
    emacs $test_path/test$1.output& 
    emacs $test_path/test$1&
else
    echo Error while compiling comp2
fi

